//POST http://localhost:8080/teach_war_exploded/hello
//POST http://localhost:8080/teach_war_exploded/minsk
//POST http://localhost:8080/teach_war_exploded/washington
//POST http://localhost:8080/teach_war_exploded/beijing