version: '3.3'
services:
  app:
    build:
      context: .
    container_name: springboot_new
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql:/db:3306/dealer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Root
    depends_on:
      - db
    ports:
      - '8081:8081'


  db:
    image: mysql:8.0.29
    container_name: mysql_8
    restart: always
    environment:
      MYSQL_DATABASE: "dealer"
      MYSQL_USER: root
      MYSQL_PASSWORD: Root
      MYSQL_ROOT_PASSWORD: Root
    ports:
      - '3308:3308'
    expose:
      - '3308'

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
volumes:
  db: