spring:
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 20MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate #none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/dealer?serverTimezone=Europe/Minsk&useSSL=false
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      leak-detection-threshold: 5000 # in msecs

  liquibase:
    change-log: 'classpath:db-migrations/changeLog.xml'
    enabled: true
springdoc:
  #  show-actuator: true
  #  use-management-port: true
  swagger-ui:
    path: /docs.html
  #    enabled: false
  api-docs:
    path: /api/docs.yaml
#    enabled: false
